# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        StgCMS
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - /backend/themes/css/jquery.treeTable.css
    - /backend/themes/css/main.css
    - /css/lightbox/jquery.lightbox.css
    - /backend/themes/css/jquery/hot-sneaks/jquery-ui.custom.css

  javascripts:
    - /backend/themes/js/jquery.treeTable.min.js
    - /backend/themes/js/main.js
    - /js/tiny_mce/tiny_mce.js
    - /backend/themes/js/jquery-ui-1.8.5.custom.min.js
    - /js/lightbox/jquery.lightbox.min.js
    - /js/pictures.js
    - /js/jquery.livequery.js
    - /js/jquery.ui.nestedSortable.js

  has_layout:     true
  layout:         layout

