<?php

/**
 * Article2TagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Article2TagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Article2TagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article2Tag');
    }
}