<?php

/**
 * ArticlesVersionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticlesVersionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticlesVersionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticlesVersion');
    }

    public function UnActiveArticleVersionAll($article_id)
    {
        $q = Doctrine_Query::create()
            ->from('ArticlesVersion av')
            ->where('av.article_id = ?', $article_id);
        
        $versions = $q->execute();
        foreach($versions as $version)
        {
            $version->setIsActive(false);
            $version->save();
        }
    }

    public function getVersionByIds($ids, $is_active = true)
    {
        $q = Doctrine_Query::create()
            ->from('ArticlesVersion av')
            ->whereIn('av.article_version_id', $ids)
            ->addWhere('av.is_active =?', $is_active);
        return $q->execute();
    }
}