<?php

/**
 * Articles2ArtCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Articles2ArtCategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Articles2ArtCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Articles2ArtCategories');
    }
}