<?php

/**
 * ArticleCustomFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleCustomFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleCustomFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleCustomField');
    }

    public function getCustomFields($id) {
        $q = $this->createQuery('acf')
                ->select('*')
                ->leftJoin('acf.ArticleCustomFieldValue acfv')
                ->andWhere('acfv.article_id = ?', $id);

        return $q->execute();
    }

}