<?php

/**
 * ArticleCustomFieldValueTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleCustomFieldValueTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleCustomFieldValueTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ArticleCustomFieldValue');
    }

    /**
     * zwraca wartosc pola
     * @param Article $article artykul
     * @param string $field nazwa pola
     * @return Doctrine_Collection pole wlasne z wartoscia
     */
    public function getByArticleAndName($article, $field) {
        $q = $this->createQuery('acfv')
                ->select('*')
                ->leftJoin('acfv.ArticleCustomField acf')
                ->andWhere('acfv.article_id = ?', $article->getPrimaryKey())
                ->andWhere('acf.name = ?', $field);

        return $q->fetchOne();
    }

    /**
     * zwraca pola wlasne artykulu
     * @param int $id id artykulu
     * @return Doctrine_Collection pola wlasne artykulu
     */
    public function getCustomFields($id) {
        $q = $this->createQuery('acfv')
                ->select('*')
                ->leftJoin('acfv.ArticleCustomField acf')
                ->andWhere('acfv.article_id = ?', $id);

        return $q->execute();
    }

    /**
     * zwraca pole wlasne po artykule i po record key pola
     * @param Article $article artykul
     * @param string $record_key record key pola
     * @return <type> pole wlasne
     */
    public function getByArticleAndRecordKey($article, $record_key) {
        $q = $this->createQuery('acfv')
                ->select('*')
                ->leftJoin('acfv.ArticleCustomField acf')
                ->andWhere('acfv.article_id = ?', $article->getPrimaryKey())
                ->andWhere('acf.record_key = ?', $record_key);

        return $q->fetchOne();
    }

}