<?php

/**
 * ArticleFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleFile');
    }
}