<?php

/**
 * ArticleGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleGallery');
    }
}