<?php

/**
 * ArticleCustomField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArticleCustomField extends BaseArticleCustomField
{

}
