<?php

/**
 * Articles2ArticlesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Articles2ArticlesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Articles2ArticlesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Articles2Articles');
    }
}