<?php

/**
 * ArticleCustomFields2ArtCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleCustomFields2ArtCategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleCustomFields2ArtCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleCustomFields2ArtCategories');
    }
}