<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory implements StgTreDoctrineRecordInterface
{
  public function isEditableRoot() // dla StgTree
  {
    return true; //jeśli w backendzie ma być niewidoczny root, to wystarczy ustawić is_active roota na 0
  }
  
  public function hasChildren() {
    return $this->getRgt() - $this->getLft() > 1;
  }
  
  public function getIndentedName()
  {
      return str_repeat('- ',$this->getLevel()).' '.$this->getName();
  }
  
  public function getParentId() {
    return $this->getNode()->hasParent() ? $this->getNode()->getParent()->getPrimaryKey() : null;
  }  
  
  public function save(Doctrine_Connection $conn = null)
  {  
      if ($this->isNew()) { $this->Metas = Metas::createAndSave(); }
        
      $r = parent::save($conn);

      $this->Metas->generateMetas($this);
      return $r;
  }
  
  public function isCurentUrl()
  {
      sfContext::getInstance()->getConfiguration()->loadHelpers(array('Url', 'Tag'));
      $url = $_SERVER["REQUEST_URI"];    
      if(url_for('category', $this) == $url)
      {
          return true;
      }
      else
      {
//          $obj = $this->getNode()->getChildren();
//          do
//          {
//              $tmp = url_for('category', $obj);
//              if($tmp == $url)
//              {
//                  return true;
//              }
//          }
//          while($obj = $obj->getNode()->getChildren());
          
          return false;
      }
      return false;
  }
  
  
}
