<?php

/**
 * Comments
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    stgcms2
 * @subpackage model
 * @author     Jerzy Biernacki <jurek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comments extends BaseComments
{
    public function save(Doctrine_Connection $conn = null)
    {
        T::cc('frontend');
        return parent::save($conn);
    }

    public function delete(Doctrine_Connection $conn = null)
    {
        T::cc('frontend');
        return parent::delete($conn);
    }


    static function removeComments($comments)
    {
        foreach($comments as $comment)
        {
            $comment->delete();
        }
    }
}
