<?php

/**
 * CommentArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommentArticle');
    }
}