<?php

/**
 * Company2CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Company2CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Company2CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Company2Category');
    }
}