<?php

/**
 * Company2TypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Company2TypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Company2TypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Company2Type');
    }
}