<?php

/**
 * Contact
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    stgcms2
 * @subpackage model
 * @author     Jerzy Biernacki <jurek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contact extends BaseContact
{
    static public function getContactForSlug()
    {
        $return = Doctrine_Query::create()->from('Contact c')->where('contact_id = ?',1)->execute();
        return $return[0];
    }
    
    /**
     * SAVES TRANSLATIONS
     */
    public function initalizeTranslations() {
      foreach(Lang::getInstance()->getAll()->toArray() as $lang) { //foreach language
        $this->Translation[$lang]; //nic z tym nie robię - wystarczy, że to się zainicjalizuje w obiekcie
      }
    }

    public static function getContactEmail() {
      return Doctrine::getTable('Contact')->getFirst()->get('form_email');
    }
    
    public static function getAdminEmail() {
      return sfGuardUser::getOneByUsername('admin')->getEmailAddress();
    }

    public function save(Doctrine_Connection $conn = null)
    {
      $this->initalizeTranslations(); // żeby zapisały się wersje językowe
        T::cc('frontend');
        return parent::save($conn);
    }

    public function delete(Doctrine_Connection $conn = null)
    {
        T::cc('frontend');
        return parent::delete($conn);
    }

    public function __toString()
    {
        return 'Kontakt';
    }
}
