<?php

/**
 * ContactQueriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactQueriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactQueriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactQueries');
    }
}