<?php

/**
 * Culture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Culture extends BaseCulture
{
  public function  save(Doctrine_Connection $conn = null) {
    $is_new = $this->isNew();

    parent::save($conn);
    if ($is_new) {
      $this->createMenus();
      $this->saveArticles(); //zapisuje wszystkie artykuły, żeby stworzyć ich wersje językowe
      $this->saveArtCategories(); //analogicznie
      $this->saveMetas(); //analogicznie
      $this->saveFiles(); //analogicznie
      $this->saveGalleries(); //analogicznie
      $this->savePictures(); //analogicznie
      $this->saveArticlesVersion(); //analogicznie
      $this->saveContact(); //analogicznie
    }
  }

  public function  delete(Doctrine_Connection $conn = null) {
    if ($this->isDeletable()) {
      $this->setIsDeleted(true);
      $this->save();
    }
  }
  
  public function  setIsActive($b) {
    if ($b == false && ! $this->canDeactivate()) {
      return false;
    }
    $this->_set('is_active', $b);
  }

  public function isDefault() {
    return (Lang::getDefaultLanguage() == $this->getPrimaryKey()) ? true : false;
  }

  public function isActive() {
    return $this->getTable()->checkIsActive($this);
  }

  public function canDeactivate() {
    return $this->isDefault() ? false : true;
  }

  public function canMakeDefault() {
    return $this->getIsDeleted() ? false : true;
  }

  public function canMoveUp() {
    return !$this->isDefault() && $this->getPosition() != $this->getTable()->createQuery()
                                                                           ->orderBy('position')
                                                                           ->limit(2)
                                                                           ->addWhere('is_deleted = false')
                                                                           ->execute()
                                                                           ->getLast()
                                                                           ->getPosition();
  }

  public function canMoveDown() {
    return !$this->isDefault() && $this->getPosition() != $this->getTable()->createQuery()
                                                                           ->orderBy('position DESC')
                                                                           ->addWhere('is_deleted = false')
                                                                           ->fetchOne()
                                                                           ->getPosition();
  }

  public function isDeletable() {
    return $this->isDefault() ? false : true;
  }

  public function saveArticles() {
    $collection = Doctrine::getTable('Articles')->findAll();
    $collection->save();
  }

  public function saveArtCategories() {
    $collection = Doctrine::getTable('ArtCategories')->findAll();
    $collection->save();
  }

  public function saveMetas() {
    $collection = Doctrine::getTable('Metas')->findAll();
    $collection->save();
  }

  public function saveFiles() {
    $collection = Doctrine::getTable('Files')->findAll();
    $collection->save();
  }

  public function saveGalleries() {
    $collection = Doctrine::getTable('Galleries')->findAll();
    $collection->save();
  }

  public function savePictures() {
    $collection = Doctrine::getTable('Pictures')->findAll();
    $collection->save();
  }

  public function saveArticlesVersion() {
    $collection = Doctrine::getTable('ArticlesVersion')->findAll();
    $collection->save();
  }

  public function saveContact() {
    $collection = Doctrine::getTable('Contact')->findAll();
    $collection->save();
  }

  /**
   * Tworzy potrzebne menu dla tej Culture
   */
  public function createMenus() {
    foreach (explode(',', stgConfig::get('menu_keys')) as $menuKey) {
      if (! Doctrine::getTable('Menus')->findMenuRoot($menuKey, $this->getLanguage())) {
        $menu = new Menus();
        $menu->setMenuKey($menuKey);
        $menu->setName($menuKey);
        $menu->setTitle($menuKey);
        $menu->setLang($this->getLanguage());
        $menu->save();

        Doctrine_Core::getTable('Menus')->getTree()->createRoot($menu);
      }
    }
  }
  
}
