<?php

/**
 * Currencies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    stgcms2
 * @subpackage model
 * @author     Jerzy Biernacki <jurek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Currency extends BaseCurrency
{
    static public function getSymbolForLanguage($language)
    {
      $apc = ApcCollection::getInstance();
      $return = $apc->get('Currency.getSymbolForLanguage.'.$language);
      if($return === false)
      {
        $symbol = self::getCurrencyForLanguage($language)->fetchOne()->getSymbol();
        $apc->add('Currency.getSymbolForLanguage.'.$language,$symbol);
        return $symbol;
      }
      else
      {
        return $return;
      }
    }

    static public function getCurrencyForLanguage($language)
    {
        $q = Doctrine_Query::create()->from('Currency')
        ->where('language = ?',$language);
        return $q;
    }
}
