<?php

/**
 * FilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Files');
    }

    public function getAllQuery()
    {
      $q = Doctrine_Query::create()->from('Files files')
          ->orderBy('files.lft')       
          ->addWhere('files.level > 0 ')
          ->addWhere('files.file IS NOT NULL')
              ;
      return $q;
    }
    
    public function getOptionsList()
    {
      $files = $this->getAllQuery()->execute();
      $return = array();
      foreach($files as $file)
      {
//        $return[$file->getPrimaryKey()] = $file;
//        $return[$file->getPrimaryKey()] = str_repeat('- ', $file->getLevel() - 1).$file->__toString();
        $return[$file->getPrimaryKey()] = $file->getPathName();
      }
      return $return;
    }

    public function doSelectForSlug($parameters)
    {
      if (isset($parameters['sf_culture'])) {
        return $this->findOneBySlugAndCulture($parameters['slug'], $parameters['sf_culture']);
      }
      else {
        return $this->findOneBySlugAndCulture($parameters['slug']);
      }
    }

    public function findOneBySlugAndCulture($slug, $culture = 'pl')
    {
        $q = $this->createQuery('f')
                ->leftJoin('f.Translation t')
                ->andWhere('t.lang = ?', $culture)
                ->andWhere('t.slug = ?', $slug);
        return $q->fetchOne();
    }
}