<?php

/**
 * Icon
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Icon extends BaseIcon {

    const MIN = 'min';
    const MAX = 'max';
    
    public static function getSubdirectories() {
        return array('original', 'min', 'max');
    }

    public static function getDir() {
        return sfConfig::get('sf_upload_dir').'/icons';
    }

    public function save(Doctrine_Connection $conn = null) {
        T::cc('frontend');
        return parent::save($conn);
    }

    public function delete(Doctrine_Connection $conn = null) {
        T::cc('frontend');
        return parent::delete($conn);
    }

    static public function getAllActive() {
        $q = Doctrine_Query::create()->from('Icon')->where('is_active = ?', true)->execute();
        return $q;
    }

    static public function getActiveFile() {
        $icon = Doctrine_Query::create()->from('Icon')->where('is_active = ?', true)->fetchOne();

        return $icon['file'];
    }

    public function switchActive() {
        if ($this->getIsActive()) {
            $this->setIsActive(false);
            $this->save();
        }
        else {
            $activeObjects = Icon::getAllActive();
            foreach ($activeObjects as $k => $o) {
                $o->setIsActive(false);
                $o->save();
            }
            $this->setIsActive(true);
            $this->save();
        }
    }

    static public function getOneByPk($pk) {
        return IconTable::getOneByPkQuery($pk)->fetchOne();
    }

    /**
     * Tworzy kod generujacy favicone
     * @param string $size rozmiar - min, max lub Icon::MIN, Icon::MAX
     * @return string
     */
    public static function generateFavicon($size = 'min') {
        $file = self::getActiveFile();
        $ext = substr($file, strrpos($file, '.') + 1);

        if($file == '') return '';

        $type = array(
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'jpe' => 'image/jpeg',
            'png' => 'image/png',
            'gif' => 'image/gif',
        );

        return '<link rel="icon" type="'.$type[$ext].'" href="/uploads/icons/'.$size.'/'.$file.'"/>';
    }

}
