<?php

/**
 * Invoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Invoice extends BaseInvoice implements InvoiceableInterface
{
    public function getNumber()
    {
        $date = $this->getInvoiceDate();
        $date = explode(' ', $date);
        $date = str_replace('-', '.', $date[0]);
        $number = $this->getPrimaryKey().'/COM/'.$date;

        return $number;
    }

    public function getName()
    {
        return 'Faktura VAT nr '.$this->getNumber();
    }
}
