<?php

/**
 * MenusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MenusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Menus');
    }

    public function findByName($name)
    {
        return Doctrine_Query::create()
            ->from('Menus m')
            ->where('m.name LIKE ?', "%$name%")
            ->execute();
    }

    public function findMenuRoot($menu_key, $lang)
    {
        // jeżeli $lang jest w formacie 'pl_PL' to zmieniam go na 'pl'
        $lang = explode('_', $lang);
        $lang = $lang[0];

        return $this->createQuery()
            ->addWhere('menu_key = ?', $menu_key)
            ->addWhere('lang = ?', $lang)
            ->addWhere('level = 0')
            ->fetchOne();
    }

    public function fetchByCultureNotDeleted()
    {
        $langs = Lang::getInstance()->getNotDeleted()->toArray();

        $rootsFromLangsIds = $this->createQuery()
            ->andWhereIn('lang', $langs)
            ->execute()
            ->getPrimaryKeys();

        return $this->createQuery()
            ->andWhereIn('root_id', $rootsFromLangsIds)
            ->orderBy('root_id, lft')
            ->execute();
    }

}