<?php

/**
 * Order
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order extends BaseOrder
{
    public function save(Doctrine_Connection $conn = null)
    {
        $order = parent::save($conn);
        InvoiceTable::getInstance()->setInvoiceFromOrder($this);
        return $order;
    }
    
    public function getPacketName()
    {
        $packets = PricesTable::getInstance()->getPackets();
        return $packets[$this->getPacket()];
    }
}
