<?php

/**
 * OrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Order');
    }

    //ustawiona flaga na is_new oznacza ze pierwszy raz dodaje firme i biore kwote zamowienia ze start_brutto a nie price_brutto
    public function addOrderFromParameters($params = array(), Profile $profile, Company $company)
    {
        $order = new Order();
        $order->setUid(md5('ocean'.time().'firm'));
        $order->setProfile($profile);
        $order->setCompany($company);
        
        
        $packet = PricesTable::getInstance()->find($params['packet']);
        
        $order->setPacket($packet->getPacket());

        $order->setValueNetto($packet->getPriceNetto());
        $order->setValueBrutto($packet->getPriceBrutto());       

        $date_from = $company->getRentFrom();
        $date_to = $company->getRentTo();        
        
        $order->setRentFrom($date_from);
        $order->setRentTo($date_to);
        
        $order->setIsPaid(0);
        $order->setPacket($packet->getPacket());
        $order->setStatus(StatusTable::getInstance()->find('New'));
        $order->save();
        return $order;
    }
    
    public function addNewOrder($params = array(), Profile $profile, Company $company)
    {
        $order = new Order();
        $order->setUid(md5('ocean'.time().'firm'));
        $order->setProfile($profile);
        $order->setCompany($company);
        
        
        $packet = PricesTable::getInstance()->find($params['packet']);
        
        $order->setPacket($packet->getPacket());
        
        $order->setValueNetto($packet->getPriceNetto());
        $order->setValueBrutto($packet->getPriceBrutto());
        
        $date_to = $company->getRentTo();        
        
        $order->setRentFrom($date_to);
        
        $rent_to = strToTime($date_to);        
        $new = $rent_to + (60*60*24*$packet->getPeriod());
        
        $order->setRentTo(date('Y-m-d H:i:s', $new));
        
        $order->setIsPaid(0);
        $order->setPacket($packet->getPacket());
        $order->setStatus(StatusTable::getInstance()->find('New'));
        $order->save();
        return $order;
    }
    
    public function addToPremiumOrder($params = array(), Profile $profile, Company $company)
    {
        $order = new Order();
        $order->setUid(md5('ocean'.time().'firm'));
        $order->setProfile($profile);
        $order->setCompany($company);
        
        
        $packet = PricesTable::getInstance()->find($params['packet']);
        
        $order->setPacket($packet->getPacket());
        
        $order->setValueNetto($packet->getPriceNetto());
        $order->setValueBrutto($packet->getPriceBrutto());
        
        $date_to = date('Y-m-d H:i:s');        
        
        $order->setRentFrom($date_to);
        
        $rent_to = strToTime($date_to);        
        $new = $rent_to + (60*60*24*$packet->getPeriod());
        
        $order->setRentTo(date('Y-m-d H:i:s', $new));
        
        $order->setIsPaid(0);
        $order->setPacket($packet->getPacket());
        $order->setStatus(StatusTable::getInstance()->find('New'));
        $order->save();
        
        $company->setPacket($packet->getPacket());
        $company->setRentTo($order->getRentTo());
        //$company->setRentFrom($order->getRentFrom());
        $company->setIsPaid(0);
        $company->save();
        
        return $order;
    }
}