<?php

/**
 * ProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profile');
    }

    public function addProfileFromParameters($params = array())
    {
        $user = new sfGuardUser();
        $user->setFirstName($params['profile_first_name']);
        $user->setLastName($params['profile_last_name']);
        $user->setEmailAddress($params['email']);
        $user->setUsername($params['email']);
        $user->setPassword($params['password']);
        $user->save();
        
        $group = sfGuardGroupTable::getInstance()->findOneByName('Klienci');
        $ug = new sfGuardUserGroup();
        $ug->setGroup($group);
        $ug->setUser($user);
        $ug->save();
        
        //$profile = $this->findOneByGuardUserId($user->getPrimaryKey());
        $profile = $user->getProfile();        
        $profile->setName($params['profile_name']);
        $profile->setCity($params['profile_city']);
        $profile->setPostCode($params['profile_post_code']);
        $profile->setState($params['profile_state']);
        $profile->setStreet($params['profile_street']);
        $profile->setNip($params['profile_nip']);
        $profile->setPhone($params['profile_phone']);
        $profile->save();
        
        $mail = "<p>Możesz sie zalogowań na dane: <br /><br />Login: <strong>".$params['email']."</strong><br />Hasło: <strong>".$params['password']."</strong><br /></p>";
        T::systemMail($params['email'], 'Konto zostało utworzone', $mail);
        
        
        
        return $profile;
    }
}