<?php

/**
 * SearchIndexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SearchIndexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SearchIndexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SearchIndex');
    }
}