<?php

/**
 * SecurityIndex
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SecurityIndex extends BaseSecurityIndex
{
  /*
   * Sprawdza czy użytkownik ma prawo do oglądania obiektu $object
   */
  public static function checkSecurity($object) {
    // prawa wymagane dla tego obiektu
    $permissionNames = Doctrine::getTable('SecurityIndex')->findPermissionNamesByObject($object);

    if (count($permissionNames)) { //obiekt jest chroniony

      $user = sfContext::getInstance()->getUser();
      if (!$user->isAuthenticated()) {
        return false; // użytkownik niezalogowany nie ma żadnych praw
      }
      
      // prawa użytkownika
      $userPermissions = $user->getGuardUser()->getPermissionNames();

      // sprawdzam, czy użytkownik ma wymagane prawa dla tego obiektu
      foreach ($permissionNames as $permission) {
        if (!in_array($permission, $userPermissions)) {
          return false;
        }
      }
    }

    // jeśli obiekt to NestedSet i obiekt ma rodzica to rodzic też musi być sprawdzony
    if ($object->getNode() && $object->getNode()->hasParent()) {
      $parent_is_suecure = self::checkSecurity($object->getNode()->getParent());
      if (!$parent_is_suecure) {
        return false;
      }
    }

    // sprawdzanie dodatkowych warunków w zależności od klasy obiektu
    switch (get_class($object))  {
      case 'Articles':
        return self::checkSecurity($object->getArtCategories()); // artykuł musi należeć do kategorii, do której mamy prawa
        break;
      case 'Files':
        $articles = $object->getArticles();
        if (count($articles)) {
          $result = false;
          foreach ($articles as $article) {
            if (self::checkSecurity($article)) { // jeżeli user ma prawa do chociażby jednego artykułu, do którego podpięty jest ten plik, to ma też prawa do pliku
              $result = true;
            }
          }
          return $result;
        }
        else {
          return true;
        }
        break;
    }

    // nie znaleziono żadnych przeszkód
    return true;
  }
}
