<?php

/**
 * SecurityIndexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SecurityIndexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SecurityIndexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SecurityIndex');
    }

    public function findObjectsByModelAndPermissionNames($model, $permissions)
    {
      $q = $this->createQuery()
                ->addWhere('model = ?', $model)
                ->andWhereIn('permission_name', $permissions)
              ;

      $searchIndexes = $q->execute();

      if (!count($searchIndexes)) {
        return null;
      }

      $objectsIds = array();
      foreach ($searchIndexes as $searchIndex) {
        $objectsIds[] = $searchIndex->getModelId();
      }

      $primaryKeys = Doctrine::getTable($model)->getIdentifierColumnNames();
      $primaryKey = reset($primaryKeys);
      $q2 = Doctrine_Query::create()
                ->from($model)
                ->andWhereIn($primaryKey, $objectsIds)
              ;

      return $q2->execute();
    }

    public function findPermissionNamesByObject($object)
    {
      $class= get_class($object);
      $q = $this->createQuery()
                ->addWhere('model = ?', get_class($object))
                ->addWhere('model_id = ?', $object->getPrimaryKey())
              ;

      $securityIndexRecords = $q->execute();

      $permissionNames = array();
      foreach ($securityIndexRecords as $record) {
        $permissionNames[] = $record->getPermissionName();
      }

      return $permissionNames;
    }
}