<?php

/**
 * SliderBanners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    stgcms2
 * @subpackage model
 * @author     Jerzy Biernacki <jurek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SliderBanners extends BaseSliderBanners
{

  public function getPath()
  {
    $path = "";
    if ($this->getUserBannerId() != null)
    {
      $banner = $this->getUserBanners();
      $path = '/uploads/user_banners/original/' . $banner->getFile();
    }
    else
    {
      $path = '/uploads/slider_banners/' . $this->getFile();
    }
    return $path;
  }

  public function setNextPosition()
  {
    $slider_id = $this->getSliderId();
    $old_position = $this->getPosition();
    $q = Doctrine_Query::create()
                    ->from('SliderBanners')
                    ->orderBy('position')
                    ->where('position >?', $old_position)
                    ->andWhere('slider_id =?', $slider_id)
                    ->limit(1);
    $old = $q->fetchOne();

    if ($old instanceof SliderBanners)
    {

      $new_position = $old->getPosition();

      $this->setPosition($new_position);
      $conn = $this->getTable()->getConnection();
      $this->save($conn);

      $old->setPosition($old_position);
      $conn = $old->getTable()->getConnection();
      $old->save($conn);
    }
  }

  public function setPrevPosition()
  {
    $slider_id = $this->getSliderId();
    $old_position = $this->getPosition();
    $q = Doctrine_Query::create()
                    ->from('SliderBanners')
                    ->orderBy('position desc')
                    ->where('position <?', $old_position)
                    ->andWhere('slider_id =?', $slider_id)
                    ->limit(1);
    $old = $q->fetchOne();
    if ($old instanceof SliderBanners)
    {
      $new_position = $old->getPosition();

      $this->setPosition($new_position);
      $conn = $this->getTable()->getConnection();
      $this->save($conn);

      $old->setPosition($old_position);
      $conn = $old->getTable()->getConnection();
      $old->save($conn);
    }
  }

  public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew())
    {
      if (!$this->getPosition()) {
        $position = Doctrine::getTable('Sliders')->find($this->getSliderId())->getNextPositionBanner();
        $this->setPosition($position);
      }
    }
    T::cc('frontend');
    return parent::save($conn);
  }

  public function delete(Doctrine_Connection $conn = null)
  {
    $slider_id = $this->getSliderId();
    if ($this->getFile() != null)
    {
      unlink(sfConfig::get('sf_upload_dir') . '/slider_banners/' . $this->getFile());
    }
    T::cc('frontend');
    parent::delete($conn);
    Doctrine::getTable('Sliders')->repairPosition($slider_id);
    return true;
  }

}
