<?php

/**
 * SliderBannersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SliderBannersTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object SliderBannersTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('SliderBanners');
  }

  public function removeBanners($user_banner_id)
  {
    $q = Doctrine_Query::create()
                    ->from('SliderBanners')
                    ->where('user_banner_id =?', $user_banner_id);
    $banners = $q->execute();
    foreach ($banners as $banner)
    {
      $banner->delete();
    }
  }

}