<?php

/**
 * SlidersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlidersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlidersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sliders');
    }

    public function repairPosition($slider_id)
    {
        $q = Doctrine_Query::create()
            ->from('SliderBanners')
            ->where('slider_id =?', $slider_id)
            ->orderBy('position asc');
        $banners = $q->execute();
        $position = 1;
        foreach($banners as $banner)
        {
            $banner->setPosition($position);
            $banner->save();
            $position++;
        }
    }

    public function getDefault()
    {
         $q = Doctrine_Query::create()
            ->from('Sliders')
            ->where('is_default =?', true)
            ->limit(1);
         return $q->fetchOne();
    }

    public function getRandomBannerBySlider($id = false)
    {
        if($id)
        {
            $slider = $this->find($id);
        }
        else
        {
            $slider = $this->getDefault();
        }

        if($slider)
        {
            $q = $slider->getSliderBannersRandomQuery();
            $q->limit(1);

            return $q->fetchOne();
        }
        return false;
    }
}