<?php

/**
 * SuperConfigTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuperConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuperConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SuperConfig');
    }

    public function retrieveList(Doctrine_Query $q)
    {
        $is_super_admin = sfContext::getInstance()->getUser()->isSuperAdmin();
        if($is_super_admin == false)
        {
            $rootAlias = $q->getRootAlias();
            $q->addWhere($rootAlias.'.is_enabled_for_users = ?',true);
        }
        return $q;
    }
}