<?php

/**
 * TagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tag');
    }

    /**
     * pobiera liste wszystkich aktywnych tagow
     */
    public function fetchAllActive() {

        $q = $this->createQuery('t')
             //->from('Tag t')
             ->leftJoin('t.Articles a')
             ->where('a.is_public=1');

        return $q->execute();
    }

    public function doSelectForSlug($parameters)
    {
      if (isset($parameters['sf_culture'])) {
        return $this->findBySlugAndCulture($parameters['slug'], $parameters['sf_culture']);
      }
      else {
        return $this->findBySlugAndCulture($parameters['slug']);
      }
    }

    public function findBySlugAndCulture($slug, $culture = 'pl')
    {
        $q = $this->createQuery('t')
             ->leftJoin('t.Articles a')
             ->where('t.slug = ?', $slug)
             ->andWhere('t.lang = ?', $culture);

        return $q->execute();
    }

}