<?php

/**
 * Themes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    stgcms2
 * @subpackage model
 * @author     Jerzy Biernacki <jurek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Themes extends BaseThemes
{

  public function save(Doctrine_Connection $conn = null)
  {
    T::cc('frontend');
    return parent::save($conn);
  }

  static public function getAllActive()
  {
    $q = Doctrine_Query::create()->from('Themes')->where('is_active = ?', true)->execute();
    return $q;
  }

  static public function getAll()
  {
    $q = Doctrine_Query::create()->from('Themes')->execute();
    return $q;
  }

  public function switchActive()
  {
    if ($this->getIsActive() == false)
    {
      $activeObjects = Themes::getAllActive();
      foreach ($activeObjects as $k => $o)
      {
        $o->setIsActive(false);
        $o->save();
      }
      $this->setIsActive(true);
      $this->save();
    }
  }

  static public function getOneByName($name)
  {
    return ThemesTable::getOneByNameQuery($name)->fetchOne();
  }

}
