<?php

/**
 * TypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Type');
    }

    public function getOptionChoices()
    {
        $return = array();
        $types = $this->findAll();
        foreach($types as $type)
        {
            $return[$type->getPrimaryKey()] = $type->getName();
        }
        return $return;
    }
    
    public function addTypesToCompany($types, $company)
    {
        $type_objects = $this->getObjectByArray($types);
        foreach($type_objects as $type)
        {
            $tmp = new Company2Type();
            $tmp->setCompany($company);
            $tmp->setType($type);
            $tmp->save();
        }
    }
    
    public function getObjectByArray($array)
    {
        $q = Doctrine_Query::create()
                ->from('Type')
                ->whereIn('id', $array);
        return $q->execute();
    }
}