<?php

/**
 * UserLogosTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserLogosTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object UserLogosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserLogos');
    }

    static public function getOneByPkQuery($pk)
    {
        $q = Doctrine_Query::create()
                ->from('UserLogos ul')
                ->where('ul.user_logo_id = ?', $pk);
        return $q;
    }

    static public function getOneByFileQuery($file)
    {
        $q = Doctrine_Query::create()
                ->from('UserLogos ul')
                ->where('ul.file = ?', $file);
        return $q;
    }

}