<?php

/**
 * UserBannersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserBannersTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object UserBannersTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('UserBanners');
  }

  static public function getOneByPkQuery($pk)
  {
    $q = Doctrine_Query::create()
                    ->from('UserBanners ub')
                    ->where('ub.user_banner_id = ?', $pk);
    return $q;
  }

  static public function getOneByFileQuery($file)
  {
    $q = Doctrine_Query::create()
                    ->from('UserBanners ub')
                    ->where('ub.file = ?', $file);
    return $q;
  }

  static public function getBannerByPage($page_id = false)
  {
    if ($page_id)
    {
      $banner = false;
      $page = Doctrine::getTable('Menus')->find($page_id);
      if ($page->getUserBannerId())
      {
        $banner = $page->getUserBannerId();
      }
      else
      {
        $q = Doctrine_Query::create()
                        ->from('Menus m')
                        ->where('m.lft <?', $page->getLft())
                        ->andWhere('m.rgt >?', $page->getRgt())
                        ->andwhere('user_banner_id >?', 0)
                        ->andWhere('level <?', $page->getLevel())
                        ->orderBy('level desc')
                        ->limit(1);
        $tmp = $q->fetchOne();
        if ($tmp)
        {
          $banner = $tmp->getUserBannerId();
        }
      }

      if ($banner)
      {
        return Doctrine::getTable('UserBanners')->find($banner);
      }
      else
      {
        return false;
      }
    }
    else
    {
      return false;
    }
  }

}