<?php

/**
 * sfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroup');
    }

  public function queryChoosableByUser($names_array) {
    return $this->createQuery()->andWhereIn('name', $names_array);
  }

  public function queryChoosableByAdmin() {
    $q = $this->createQuery()
              ->orderBy('id')
            ;

    if (! $is_super_admin = sfContext::getInstance()->getUser()->getGuardUser()->getIsSuperAdmin()) {
      if ($string = stgConfig::get('sf_guard_group_not_showable')) {
        $q->andWhereNotIn('name', explode(',', $string));
      }
    }
    return $q;
  }

  public function findOrCreateByName($name) {
    $object = $this->findOneByName($name);
    if (!$object) {
      $object = new sfGuardGroup();
      $object->setName($name);
      $object->setDescription($name);
      $object->save();
    }

    return $object;
  }
}