<?php

/**
 * sfGuardPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardPermissionTable extends PluginsfGuardPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardPermission');
    }

    public function findByNames($permission_names) {
      return $this->createQuery()
              ->andWhereIn('name', $permission_names)
              ->execute();
    }

  public function findOrCreateByName($name) {
    $object = $this->findOneByName($name);
    if (!$object) {
      $object = new sfGuardPermission();
      $object->setName($name);
      $object->setDescription($name);
      $object->save();
    }

    return $object;
  }
}