<?php

/**
 * sfGuardGroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupPermissionTable extends PluginsfGuardGroupPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroupPermission');
    }

    public function unsetPermission($group_name, $permission_name)
    {
      $group = sfGuardGroupTable::getInstance()->findOneByName($group_name);
      $permission = sfGuardPermissionTable::getInstance()->findOneByName($permission_name);

      if ($group && $permission) {
        $q = $this->createQuery()
              ->addWhere('group_id = ?', $group->getPrimaryKey())
              ->addWhere('permission_id = ?', $permission->getPrimaryKey());
        $q->execute()->delete();
      }
    }

    public function addPermission($group_name, $permission_name)
    {
      $group = sfGuardGroupTable::getInstance()->findOneByName($group_name);
      $permission = sfGuardPermissionTable::getInstance()->findOneByName($permission_name);

      if ($group && $permission && !$this->hasPermission($group_name, $permission_name)) {
        $tmp = new sfGuardGroupPermission();
        $tmp->setGroup($group);
        $tmp->setPermission($permission);
        $tmp->save();
        unset($tmp);
      }
    }

    public function hasPermission($group_name, $permission_name)
    {
      $group = sfGuardGroupTable::getInstance()->findOneByName($group_name);
      $permission = sfGuardPermissionTable::getInstance()->findOneByName($permission_name);

      $q = $this->createQuery()
            ->addWhere('group_id = ?', $group->getPrimaryKey())
            ->addWhere('permission_id = ?', $permission->getPrimaryKey());
      $q->fetchOne();

      return $q ? true : false;
    }
}