<?php

/**
 * sfGuardUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserGroupTable extends PluginsfGuardUserGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserGroup');
    }

    public function unlinkAllUnlinkableGroupsExcept($exceptGroups, $user) {
      $groups = Doctrine::getTable('sfGuardGroup')->queryChoosableByAdmin()->execute();
      
      $q = $this->createQuery()
            ->addWhere('user_id = ?', $user->getPrimaryKey())
            ->andWhereIn('group_id', $groups->getPrimaryKeys())
              ;

      foreach ($exceptGroups as $group) {
        $q->addWhere('group_id != ?', $group->getPrimaryKey());
      }

      foreach ($q->execute() as $record) {
        $record->delete();
      }
    }
}