generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:  nothing

    config:
      actions:
        _new:
          credentials:  [sf_guard_group_allow]
        _edit:
          credentials:  [sf_guard_group_allow]
        _delete:
          credentials:  [sf_guard_group_allow]
      fields:  ~
      list:    ~
      filter:
        display: [name]
      form:    ~
      edit:    ~
      new:     ~
