<?php

/**
 * BaseArticleFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $file_id
 * @property Articles $Articles
 * @property Files $Files
 * 
 * @method integer     getArticleId()  Returns the current record's "article_id" value
 * @method integer     getFileId()     Returns the current record's "file_id" value
 * @method Articles    getArticles()   Returns the current record's "Articles" value
 * @method Files       getFiles()      Returns the current record's "Files" value
 * @method ArticleFile setArticleId()  Sets the current record's "article_id" value
 * @method ArticleFile setFileId()     Sets the current record's "file_id" value
 * @method ArticleFile setArticles()   Sets the current record's "Articles" value
 * @method ArticleFile setFiles()      Sets the current record's "Files" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_article_file');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('file_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Articles', array(
             'local' => 'article_id',
             'foreign' => 'article_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Files', array(
             'local' => 'file_id',
             'foreign' => 'file_id',
             'onDelete' => 'CASCADE'));
    }
}