<?php

/**
 * BaseIcon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $file
 * @property boolean $is_active
 * @property string $record_key
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getTitle()      Returns the current record's "title" value
 * @method string  getFile()       Returns the current record's "file" value
 * @method boolean getIsActive()   Returns the current record's "is_active" value
 * @method string  getRecordKey()  Returns the current record's "record_key" value
 * @method Icon    setId()         Sets the current record's "id" value
 * @method Icon    setTitle()      Sets the current record's "title" value
 * @method Icon    setFile()       Sets the current record's "file" value
 * @method Icon    setIsActive()   Sets the current record's "is_active" value
 * @method Icon    setRecordKey()  Sets the current record's "record_key" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIcon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_icons');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Krótki tekst',
             'length' => 512,
             ));
        $this->hasColumn('file', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 512,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('record_key', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}