<?php

/**
 * BaseArticles2ArtCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $artcategory_id
 * @property Articles $Article
 * @property ArtCategories $ArtCategory
 * 
 * @method integer                getArticleId()      Returns the current record's "article_id" value
 * @method integer                getArtcategoryId()  Returns the current record's "artcategory_id" value
 * @method Articles               getArticle()        Returns the current record's "Article" value
 * @method ArtCategories          getArtCategory()    Returns the current record's "ArtCategory" value
 * @method Articles2ArtCategories setArticleId()      Sets the current record's "article_id" value
 * @method Articles2ArtCategories setArtcategoryId()  Sets the current record's "artcategory_id" value
 * @method Articles2ArtCategories setArticle()        Sets the current record's "Article" value
 * @method Articles2ArtCategories setArtCategory()    Sets the current record's "ArtCategory" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticles2ArtCategories extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_articles_2_art_categories');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('artcategory_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Articles as Article', array(
             'local' => 'article_id',
             'foreign' => 'article_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ArtCategories as ArtCategory', array(
             'local' => 'artcategory_id',
             'foreign' => 'artcategory_id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}