<?php

/**
 * BaseArticle2Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $tag_id
 * @property Articles $Article
 * @property Tag $Tag
 * 
 * @method integer     getArticleId()  Returns the current record's "article_id" value
 * @method integer     getTagId()      Returns the current record's "tag_id" value
 * @method Articles    getArticle()    Returns the current record's "Article" value
 * @method Tag         getTag()        Returns the current record's "Tag" value
 * @method Article2Tag setArticleId()  Sets the current record's "article_id" value
 * @method Article2Tag setTagId()      Sets the current record's "tag_id" value
 * @method Article2Tag setArticle()    Sets the current record's "Article" value
 * @method Article2Tag setTag()        Sets the current record's "Tag" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle2Tag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_article_2_tag');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Articles as Article', array(
             'local' => 'article_id',
             'foreign' => 'article_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}