<?php

/**
 * BaseCompany2Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property integer $category_id
 * @property Company $Company
 * @property Category $Category
 * 
 * @method integer          getCompanyId()   Returns the current record's "company_id" value
 * @method integer          getCategoryId()  Returns the current record's "category_id" value
 * @method Company          getCompany()     Returns the current record's "Company" value
 * @method Category         getCategory()    Returns the current record's "Category" value
 * @method Company2Category setCompanyId()   Sets the current record's "company_id" value
 * @method Company2Category setCategoryId()  Sets the current record's "category_id" value
 * @method Company2Category setCompany()     Sets the current record's "Company" value
 * @method Company2Category setCategory()    Sets the current record's "Category" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompany2Category extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_company_2_category');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}