<?php

/**
 * BaseArticleCustomField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $type
 * @property string $record_key
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $ArtCategories
 * @property Doctrine_Collection $ArticleCustomFieldValue
 * @property Doctrine_Collection $ArticleCustomFields2ArtCategories
 * 
 * @method string              getName()                              Returns the current record's "name" value
 * @method string              getType()                              Returns the current record's "type" value
 * @method string              getRecordKey()                         Returns the current record's "record_key" value
 * @method Doctrine_Collection getArticles()                          Returns the current record's "Articles" collection
 * @method Doctrine_Collection getArtCategories()                     Returns the current record's "ArtCategories" collection
 * @method Doctrine_Collection getArticleCustomFieldValue()           Returns the current record's "ArticleCustomFieldValue" collection
 * @method Doctrine_Collection getArticleCustomFields2ArtCategories() Returns the current record's "ArticleCustomFields2ArtCategories" collection
 * @method ArticleCustomField  setName()                              Sets the current record's "name" value
 * @method ArticleCustomField  setType()                              Sets the current record's "type" value
 * @method ArticleCustomField  setRecordKey()                         Sets the current record's "record_key" value
 * @method ArticleCustomField  setArticles()                          Sets the current record's "Articles" collection
 * @method ArticleCustomField  setArtCategories()                     Sets the current record's "ArtCategories" collection
 * @method ArticleCustomField  setArticleCustomFieldValue()           Sets the current record's "ArticleCustomFieldValue" collection
 * @method ArticleCustomField  setArticleCustomFields2ArtCategories() Sets the current record's "ArticleCustomFields2ArtCategories" collection
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleCustomField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_article_custom_field');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('record_key', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Articles', array(
             'refClass' => 'ArticleCustomFieldValue',
             'local' => 'id',
             'foreign' => 'article_id'));

        $this->hasMany('ArtCategories', array(
             'refClass' => 'ArticleCustomFields2ArtCategories',
             'local' => 'id',
             'foreign' => 'artcategory_id'));

        $this->hasMany('ArticleCustomFieldValue', array(
             'local' => 'id',
             'foreign' => 'field_id'));

        $this->hasMany('ArticleCustomFields2ArtCategories', array(
             'local' => 'id',
             'foreign' => 'field_id'));
    }
}