<?php

/**
 * BaseArticleCustomFields2ArtCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $artcategory_id
 * @property integer $field_id
 * @property ArtCategories $ArtCategories
 * @property ArticleCustomField $ArticleCustomField
 * 
 * @method integer                           getArtcategoryId()      Returns the current record's "artcategory_id" value
 * @method integer                           getFieldId()            Returns the current record's "field_id" value
 * @method ArtCategories                     getArtCategories()      Returns the current record's "ArtCategories" value
 * @method ArticleCustomField                getArticleCustomField() Returns the current record's "ArticleCustomField" value
 * @method ArticleCustomFields2ArtCategories setArtcategoryId()      Sets the current record's "artcategory_id" value
 * @method ArticleCustomFields2ArtCategories setFieldId()            Sets the current record's "field_id" value
 * @method ArticleCustomFields2ArtCategories setArtCategories()      Sets the current record's "ArtCategories" value
 * @method ArticleCustomFields2ArtCategories setArticleCustomField() Sets the current record's "ArticleCustomField" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleCustomFields2ArtCategories extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_article_custom_field_2_artcategories');
        $this->hasColumn('artcategory_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('field_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ArtCategories', array(
             'local' => 'artcategory_id',
             'foreign' => 'artcategory_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ArticleCustomField', array(
             'local' => 'field_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}