<?php

/**
 * BaseComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $comment_id
 * @property string $title
 * @property clob $content
 * @property string $author
 * @property string $email
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $Galleries
 * @property Doctrine_Collection $ArticleComment
 * 
 * @method integer             getCommentId()      Returns the current record's "comment_id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method clob                getContent()        Returns the current record's "content" value
 * @method string              getAuthor()         Returns the current record's "author" value
 * @method string              getEmail()          Returns the current record's "email" value
 * @method Doctrine_Collection getArticles()       Returns the current record's "Articles" collection
 * @method Doctrine_Collection getGalleries()      Returns the current record's "Galleries" collection
 * @method Doctrine_Collection getArticleComment() Returns the current record's "ArticleComment" collection
 * @method Comments            setCommentId()      Sets the current record's "comment_id" value
 * @method Comments            setTitle()          Sets the current record's "title" value
 * @method Comments            setContent()        Sets the current record's "content" value
 * @method Comments            setAuthor()         Sets the current record's "author" value
 * @method Comments            setEmail()          Sets the current record's "email" value
 * @method Comments            setArticles()       Sets the current record's "Articles" collection
 * @method Comments            setGalleries()      Sets the current record's "Galleries" collection
 * @method Comments            setArticleComment() Sets the current record's "ArticleComment" collection
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_comments');
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => true,
             'length' => 65532,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Articles', array(
             'refClass' => 'CommentArticle',
             'local' => 'comment_id',
             'foreign' => 'article_id'));

        $this->hasMany('Galleries', array(
             'refClass' => 'CommentGallery',
             'local' => 'comment_id',
             'foreign' => 'gallery_id'));

        $this->hasMany('CommentArticle as ArticleComment', array(
             'local' => 'comment_id',
             'foreign' => 'comment_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}