<?php

/**
 * BaseCommentGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $comment_id
 * @property integer $gallery_id
 * @property Comments $Comments
 * @property Galleries $Galleries
 * 
 * @method integer        getCommentId()  Returns the current record's "comment_id" value
 * @method integer        getGalleryId()  Returns the current record's "gallery_id" value
 * @method Comments       getComments()   Returns the current record's "Comments" value
 * @method Galleries      getGalleries()  Returns the current record's "Galleries" value
 * @method CommentGallery setCommentId()  Sets the current record's "comment_id" value
 * @method CommentGallery setGalleryId()  Sets the current record's "gallery_id" value
 * @method CommentGallery setComments()   Sets the current record's "Comments" value
 * @method CommentGallery setGalleries()  Sets the current record's "Galleries" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommentGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_comment_gallery');
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comments', array(
             'local' => 'comment_id',
             'foreign' => 'comment_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Galleries', array(
             'local' => 'gallery_id',
             'foreign' => 'gallery_id',
             'onDelete' => 'CASCADE'));
    }
}