<?php

/**
 * BaseCulture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $language
 * @property string $country
 * @property string $label
 * @property boolean $is_active
 * @property boolean $is_deleted
 * 
 * @method string  getLanguage()   Returns the current record's "language" value
 * @method string  getCountry()    Returns the current record's "country" value
 * @method string  getLabel()      Returns the current record's "label" value
 * @method boolean getIsActive()   Returns the current record's "is_active" value
 * @method boolean getIsDeleted()  Returns the current record's "is_deleted" value
 * @method Culture setLanguage()   Sets the current record's "language" value
 * @method Culture setCountry()    Sets the current record's "country" value
 * @method Culture setLabel()      Sets the current record's "label" value
 * @method Culture setIsActive()   Sets the current record's "is_active" value
 * @method Culture setIsDeleted()  Sets the current record's "is_deleted" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCulture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_culture');
        $this->hasColumn('language', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('is_deleted', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($sortable0);
    }
}