<?php

/**
 * BaseSliderBanners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $slider_banner_id
 * @property integer $slider_id
 * @property string $name
 * @property string $link
 * @property integer $user_banner_id
 * @property string $file
 * @property integer $position
 * @property string $target
 * @property UserBanners $UserBanners
 * @property Sliders $Sliders
 * 
 * @method integer       getSliderBannerId()   Returns the current record's "slider_banner_id" value
 * @method integer       getSliderId()         Returns the current record's "slider_id" value
 * @method string        getName()             Returns the current record's "name" value
 * @method string        getLink()             Returns the current record's "link" value
 * @method integer       getUserBannerId()     Returns the current record's "user_banner_id" value
 * @method string        getFile()             Returns the current record's "file" value
 * @method integer       getPosition()         Returns the current record's "position" value
 * @method string        getTarget()           Returns the current record's "target" value
 * @method UserBanners   getUserBanners()      Returns the current record's "UserBanners" value
 * @method Sliders       getSliders()          Returns the current record's "Sliders" value
 * @method SliderBanners setSliderBannerId()   Sets the current record's "slider_banner_id" value
 * @method SliderBanners setSliderId()         Sets the current record's "slider_id" value
 * @method SliderBanners setName()             Sets the current record's "name" value
 * @method SliderBanners setLink()             Sets the current record's "link" value
 * @method SliderBanners setUserBannerId()     Sets the current record's "user_banner_id" value
 * @method SliderBanners setFile()             Sets the current record's "file" value
 * @method SliderBanners setPosition()         Sets the current record's "position" value
 * @method SliderBanners setTarget()           Sets the current record's "target" value
 * @method SliderBanners setUserBanners()      Sets the current record's "UserBanners" value
 * @method SliderBanners setSliders()          Sets the current record's "Sliders" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSliderBanners extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_slider_banners');
        $this->hasColumn('slider_banner_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('slider_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('user_banner_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('file', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 512,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('target', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '_self',
             'length' => 255,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserBanners', array(
             'local' => 'user_banner_id',
             'foreign' => 'user_banner_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Sliders', array(
             'local' => 'slider_id',
             'foreign' => 'slider_id',
             'onDelete' => 'CASCADE'));
    }
}