<?php

/**
 * BaseCommentArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $comment_id
 * @property integer $article_id
 * @property Comments $Comments
 * @property Articles $Articles
 * 
 * @method integer        getCommentId()  Returns the current record's "comment_id" value
 * @method integer        getArticleId()  Returns the current record's "article_id" value
 * @method Comments       getComments()   Returns the current record's "Comments" value
 * @method Articles       getArticles()   Returns the current record's "Articles" value
 * @method CommentArticle setCommentId()  Sets the current record's "comment_id" value
 * @method CommentArticle setArticleId()  Sets the current record's "article_id" value
 * @method CommentArticle setComments()   Sets the current record's "Comments" value
 * @method CommentArticle setArticles()   Sets the current record's "Articles" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommentArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_comment_article');
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comments', array(
             'local' => 'comment_id',
             'foreign' => 'comment_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Articles', array(
             'local' => 'article_id',
             'foreign' => 'article_id',
             'onDelete' => 'CASCADE'));
    }
}