<?php

/**
 * BaseArticleCustomFieldValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $field_id
 * @property string $value
 * @property Articles $Articles
 * @property ArticleCustomField $ArticleCustomField
 * 
 * @method integer                 getArticleId()          Returns the current record's "article_id" value
 * @method integer                 getFieldId()            Returns the current record's "field_id" value
 * @method string                  getValue()              Returns the current record's "value" value
 * @method Articles                getArticles()           Returns the current record's "Articles" value
 * @method ArticleCustomField      getArticleCustomField() Returns the current record's "ArticleCustomField" value
 * @method ArticleCustomFieldValue setArticleId()          Sets the current record's "article_id" value
 * @method ArticleCustomFieldValue setFieldId()            Sets the current record's "field_id" value
 * @method ArticleCustomFieldValue setValue()              Sets the current record's "value" value
 * @method ArticleCustomFieldValue setArticles()           Sets the current record's "Articles" value
 * @method ArticleCustomFieldValue setArticleCustomField() Sets the current record's "ArticleCustomField" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleCustomFieldValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_article_custom_field_values');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('field_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('value', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1024,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Articles', array(
             'local' => 'article_id',
             'foreign' => 'article_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ArticleCustomField', array(
             'local' => 'field_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}