<?php

/**
 * BaseStgLogUserActions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $user
 * @property string $module
 * @property string $action
 * @property string $params
 * @property string $sf_format
 * 
 * @method string            getUser()      Returns the current record's "user" value
 * @method string            getModule()    Returns the current record's "module" value
 * @method string            getAction()    Returns the current record's "action" value
 * @method string            getParams()    Returns the current record's "params" value
 * @method string            getSfFormat()  Returns the current record's "sf_format" value
 * @method StgLogUserActions setUser()      Sets the current record's "user" value
 * @method StgLogUserActions setModule()    Sets the current record's "module" value
 * @method StgLogUserActions setAction()    Sets the current record's "action" value
 * @method StgLogUserActions setParams()    Sets the current record's "params" value
 * @method StgLogUserActions setSfFormat()  Sets the current record's "sf_format" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStgLogUserActions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_stg_log_user_actions');
        $this->hasColumn('user', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'ERROR_NO_USER_SPECIFIED',
             'length' => 255,
             ));
        $this->hasColumn('module', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'ERROR_NO_MODULE_SPECIFIED',
             'length' => 255,
             ));
        $this->hasColumn('action', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'ERROR_NO_ACTION_SPECIFIED',
             'length' => 255,
             ));
        $this->hasColumn('params', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'NO_PARAMS_SPECIFIED',
             'length' => 255,
             ));
        $this->hasColumn('sf_format', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'NO_SF_FORMAT_SPECIFIED',
             'length' => 255,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}