<?php

/**
 * BasePictures
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $picture_id
 * @property integer $gallery_id
 * @property integer $erp_zd_zdjecieid
 * @property string $file
 * @property string $title
 * @property integer $rate_sum
 * @property integer $rate_hits
 * @property boolean $is_lang_active
 * @property Galleries $Galleries
 * @property Galleries $GalleryWhereDefault
 * 
 * @method integer   getPictureId()           Returns the current record's "picture_id" value
 * @method integer   getGalleryId()           Returns the current record's "gallery_id" value
 * @method integer   getErpZdZdjecieid()      Returns the current record's "erp_zd_zdjecieid" value
 * @method string    getFile()                Returns the current record's "file" value
 * @method string    getTitle()               Returns the current record's "title" value
 * @method integer   getRateSum()             Returns the current record's "rate_sum" value
 * @method integer   getRateHits()            Returns the current record's "rate_hits" value
 * @method boolean   getIsLangActive()        Returns the current record's "is_lang_active" value
 * @method Galleries getGalleries()           Returns the current record's "Galleries" value
 * @method Galleries getGalleryWhereDefault() Returns the current record's "GalleryWhereDefault" value
 * @method Pictures  setPictureId()           Sets the current record's "picture_id" value
 * @method Pictures  setGalleryId()           Sets the current record's "gallery_id" value
 * @method Pictures  setErpZdZdjecieid()      Sets the current record's "erp_zd_zdjecieid" value
 * @method Pictures  setFile()                Sets the current record's "file" value
 * @method Pictures  setTitle()               Sets the current record's "title" value
 * @method Pictures  setRateSum()             Sets the current record's "rate_sum" value
 * @method Pictures  setRateHits()            Sets the current record's "rate_hits" value
 * @method Pictures  setIsLangActive()        Sets the current record's "is_lang_active" value
 * @method Pictures  setGalleries()           Sets the current record's "Galleries" value
 * @method Pictures  setGalleryWhereDefault() Sets the current record's "GalleryWhereDefault" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePictures extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_pictures');
        $this->hasColumn('picture_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('erp_zd_zdjecieid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('rate_sum', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('rate_hits', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('is_lang_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Galleries', array(
             'local' => 'gallery_id',
             'foreign' => 'gallery_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Galleries as GalleryWhereDefault', array(
             'local' => 'picture_id',
             'foreign' => 'default_picture_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'of_pictures_translation',
             'fields' => 
             array(
              0 => 'title',
              1 => 'is_lang_active',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}