<?php

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $message
 * @property clob $description
 * @property string $name
 * @property clob $content
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getMessage()     Returns the current record's "message" value
 * @method clob    getDescription() Returns the current record's "description" value
 * @method string  getName()        Returns the current record's "name" value
 * @method clob    getContent()     Returns the current record's "content" value
 * @method Message setId()          Sets the current record's "id" value
 * @method Message setMessage()     Sets the current record's "message" value
 * @method Message setDescription() Sets the current record's "description" value
 * @method Message setName()        Sets the current record's "name" value
 * @method Message setContent()     Sets the current record's "content" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_message');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => true,
             'default' => '',
             'length' => 65532,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => true,
             'default' => '',
             'length' => 65532,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}