<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $guard_user_id
 * @property string $name
 * @property string $city
 * @property string $post_code
 * @property string $street
 * @property string $state
 * @property string $nip
 * @property string $phone
 * @property sfGuardUser $GuardUser
 * @property Company $Company
 * @property Doctrine_Collection $Order
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getGuardUserId()   Returns the current record's "guard_user_id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getCity()          Returns the current record's "city" value
 * @method string              getPostCode()      Returns the current record's "post_code" value
 * @method string              getStreet()        Returns the current record's "street" value
 * @method string              getState()         Returns the current record's "state" value
 * @method string              getNip()           Returns the current record's "nip" value
 * @method string              getPhone()         Returns the current record's "phone" value
 * @method sfGuardUser         getGuardUser()     Returns the current record's "GuardUser" value
 * @method Company             getCompany()       Returns the current record's "Company" value
 * @method Doctrine_Collection getOrder()         Returns the current record's "Order" collection
 * @method Profile             setId()            Sets the current record's "id" value
 * @method Profile             setGuardUserId()   Sets the current record's "guard_user_id" value
 * @method Profile             setName()          Sets the current record's "name" value
 * @method Profile             setCity()          Sets the current record's "city" value
 * @method Profile             setPostCode()      Sets the current record's "post_code" value
 * @method Profile             setStreet()        Sets the current record's "street" value
 * @method Profile             setState()         Sets the current record's "state" value
 * @method Profile             setNip()           Sets the current record's "nip" value
 * @method Profile             setPhone()         Sets the current record's "phone" value
 * @method Profile             setGuardUser()     Sets the current record's "GuardUser" value
 * @method Profile             setCompany()       Sets the current record's "Company" value
 * @method Profile             setOrder()         Sets the current record's "Order" collection
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_profile');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('post_code', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('street', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('state', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('nip', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as GuardUser', array(
             'local' => 'guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Company', array(
             'local' => 'id',
             'foreign' => 'profile_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Order', array(
             'local' => 'id',
             'foreign' => 'profile_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}