<?php

/**
 * BaseStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $name
 * @property Doctrine_Collection $Orders
 * 
 * @method string              getId()     Returns the current record's "id" value
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getOrders() Returns the current record's "Orders" collection
 * @method Status              setId()     Sets the current record's "id" value
 * @method Status              setName()   Sets the current record's "name" value
 * @method Status              setOrders() Sets the current record's "Orders" collection
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_status');
        $this->hasColumn('id', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Order as Orders', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}