<?php

/**
 * BaseStats
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $email_id
 * @property integer $company_id
 * @property Company $Company
 * @property Email $Email
 * 
 * @method integer getEmailId()    Returns the current record's "email_id" value
 * @method integer getCompanyId()  Returns the current record's "company_id" value
 * @method Company getCompany()    Returns the current record's "Company" value
 * @method Email   getEmail()      Returns the current record's "Email" value
 * @method Stats   setEmailId()    Sets the current record's "email_id" value
 * @method Stats   setCompanyId()  Sets the current record's "company_id" value
 * @method Stats   setCompany()    Sets the current record's "Company" value
 * @method Stats   setEmail()      Sets the current record's "Email" value
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStats extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_stats');
        $this->hasColumn('email_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Email', array(
             'local' => 'email_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}