<?php

/**
 * BaseFiles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_id
 * @property string $name
 * @property string $description
 * @property string $file
 * @property boolean $is_active
 * @property boolean $is_lang_active
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $ArticleFile
 * 
 * @method integer             getFileId()         Returns the current record's "file_id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method string              getFile()           Returns the current record's "file" value
 * @method boolean             getIsActive()       Returns the current record's "is_active" value
 * @method boolean             getIsLangActive()   Returns the current record's "is_lang_active" value
 * @method Doctrine_Collection getArticles()       Returns the current record's "Articles" collection
 * @method Doctrine_Collection getArticleFile()    Returns the current record's "ArticleFile" collection
 * @method Files               setFileId()         Sets the current record's "file_id" value
 * @method Files               setName()           Sets the current record's "name" value
 * @method Files               setDescription()    Sets the current record's "description" value
 * @method Files               setFile()           Sets the current record's "file" value
 * @method Files               setIsActive()       Sets the current record's "is_active" value
 * @method Files               setIsLangActive()   Sets the current record's "is_lang_active" value
 * @method Files               setArticles()       Sets the current record's "Articles" collection
 * @method Files               setArticleFile()    Sets the current record's "ArticleFile" collection
 * 
 * @package    sell4
 * @subpackage model
 * @author     Wojciech Piestrak <wojtek@studiotg.pl>, Paweł Sałajczyk <pawel@studiotg.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFiles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('of_files');
        $this->hasColumn('file_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Nazwa pliku lub katalogu',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Opis zawartości',
             'length' => 512,
             ));
        $this->hasColumn('file', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 512,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('is_lang_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Articles', array(
             'refClass' => 'ArticleFile',
             'local' => 'file_id',
             'foreign' => 'file_id'));

        $this->hasMany('ArticleFile', array(
             'local' => 'file_id',
             'foreign' => 'file_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'of_files_translation',
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
              2 => 'is_lang_active',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'canUpdate' => true,
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
             ),
             'indexName' => 'files_slug',
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
        $this->actAs($i18n0);
    }
}