generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StgLogUserActions
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          stg_log_user_actions
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:  nothing

    config:
      actions:
        _index:
          credentials:  [SUPER_ADMINISTRATOR]
      fields:  ~
      list:
        title: "Logi cms'a"
        object_actions: {}
        batch_actions:  {}
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
